@TheBorrowedChapter_HostAddress = http://localhost:5097

GET {{TheBorrowedChapter_HostAddress}}/api/books
Accept: application/json

###

GET {{TheBorrowedChapter_HostAddress}}/api/members
Accept: application/json

###

GET {{TheBorrowedChapter_HostAddress}}/api/borrow-records
Accept: application/json

###
